### ISSUE TITLE
Github password when running build.sh

### ISSUE THREAD

**Issue by adamdai** [sfu-arch/uir-docker#1]
When I run ./build.sh, the script starts cloning the 'dandelion-generator' repo and I am prompted for 'git@cs-git-research.cs.surrey.sfu.ca's password: '. Is this available somewhere or am I do something wrong?

```$ ./build.sh
mkdir: cannot create directory ‘repos’: File exists
~/uir-docker/repos ~/uir-docker
Cloning into 'dandelion-generator'...
git@cs-git-research.cs.surrey.sfu.ca's password: ```

**Comment by amsharifian** [comment]
Thanks @adamdai . We had forgotten to update those links. I updated the links and `build.sh` should start working now.
